name: uninstall-helm-releases
description: ''
inputs:
  releases:
    description: ''
    required: true
runs:
  using: composite
  steps:
    - run: |
        for RELEASE in ${{ inputs.releases }}; do
          source "${RELEASE}/parameters"
          helm uninstall ${RELEASE_NAME} --namespace ${NAMESPACE} --debug
        done
      shell: bash